import type { Product } from '@/types/product';

export const products: Product[] = [
  {
    id: 101,
    updatedAt: '2025/01/12',
    status: '出品中',
    prefecture: '大阪府',
    maker: 'SANKYO',
    name: 'フィーバー 機動戦士ガンダムユニコーン',
    type: '本体',
    quantity: 6,
    price: 325000,
    removalDate: '2025/01/31',
    replyTime: '30分',
    sellerName: '梅田ホール',
    note: '役物良好 / 盤面美品',
    shippingUnit: 1,
    handlingUnit: 2,
    allowSplitSale: true,
    hasNailSheet: true,
    hasManual: true,
    allowPickup: false,
    removalStatus: '未撤去',
    shippingSpecifyDate: '即時手配可',
    warehouseName: '大阪北倉庫',
  },
  {
    id: 102,
    updatedAt: '2025/01/09',
    status: '出品中',
    prefecture: '神奈川県',
    maker: 'SANYO',
    name: 'P大海物語5',
    type: '本体',
    quantity: 10,
    price: 275000,
    removalDate: '2025/02/15',
    replyTime: '1時間',
    sellerName: '湘南スロット',
    note: 'CRユニット付属 / 台車手配可',
    shippingUnit: 1,
    handlingUnit: 1,
    allowSplitSale: true,
    hasNailSheet: false,
    hasManual: true,
    allowPickup: true,
    removalStatus: '撤去済',
    shippingSpecifyDate: '2/20以降',
    warehouseName: '湘南ロジスティクス',
  },
  {
    id: 103,
    updatedAt: '2024/12/28',
    status: '成約済',
    prefecture: '東京都',
    maker: 'KYORAKU',
    name: 'ぱちんこ 新・必殺仕置人S',
    type: '本体',
    quantity: 4,
    price: 198000,
    removalDate: '2025/01/05',
    replyTime: '2時間',
    sellerName: '新宿ステーション',
    shippingUnit: 2,
    handlingUnit: 2,
    allowSplitSale: false,
    hasNailSheet: true,
    hasManual: false,
    allowPickup: false,
    removalStatus: '撤去済',
    shippingSpecifyDate: '応相談',
    warehouseName: '都内第1倉庫',
  },
  {
    id: 104,
    updatedAt: '2025/01/04',
    status: '出品中',
    prefecture: '北海道',
    maker: 'DAIICHI',
    name: 'スマパチ ソードアート・オンライン',
    type: '本体',
    quantity: 3,
    price: 348000,
    removalDate: '2025/02/01',
    replyTime: '45分',
    sellerName: '札幌レジャー館',
    note: '島配線セット相談可',
    shippingUnit: 1,
    handlingUnit: 2,
    allowSplitSale: false,
    hasNailSheet: false,
    hasManual: true,
    allowPickup: false,
    removalStatus: '未撤去',
    shippingSpecifyDate: '2/5出荷目安',
    warehouseName: '札幌ハブ倉庫',
  },
  {
    id: 105,
    updatedAt: '2025/01/10',
    status: '下書き',
    prefecture: '愛知県',
    maker: 'YAMASA',
    name: 'スマスロ モンキーターンV',
    type: 'セルのみ',
    quantity: 8,
    price: 158000,
    removalDate: '2025/03/01',
    replyTime: '1時間',
    sellerName: '名古屋スロット専門館',
    note: 'ヘッドホン端子増設',
    shippingUnit: 2,
    handlingUnit: 2,
    allowSplitSale: true,
    hasNailSheet: false,
    hasManual: true,
    allowPickup: true,
    removalStatus: '未撤去',
    shippingSpecifyDate: '3/3指定可',
    warehouseName: '中部物流センター',
  },
  {
    id: 106,
    updatedAt: '2025/01/02',
    status: '出品中',
    prefecture: '福岡県',
    maker: 'HEIWA',
    name: 'Pルパン三世 THE FIRST',
    type: '本体',
    quantity: 5,
    price: 210000,
    removalDate: '2025/01/25',
    replyTime: '30分',
    sellerName: '博多プラザ',
    shippingUnit: 1,
    handlingUnit: 1,
    allowSplitSale: true,
    hasNailSheet: true,
    hasManual: true,
    allowPickup: false,
    removalStatus: '撤去済',
    shippingSpecifyDate: '1/30以降',
    warehouseName: '九州第2倉庫',
  },
];
