import type { Product } from '@/types/product';

export const products: Product[] = [
  {
    id: 101,
    updatedAt: '2025/01/12',
    status: '出品中',
    prefecture: '大阪府',
    maker: 'SANKYO',
    name: 'フィーバー 機動戦士ガンダムユニコーン',
    type: '本体',
    quantity: 6,
    price: 325000,
    removalDate: '2025/01/31',
    replyTime: '30分',
    sellerName: '梅田ホール',
    note: '役物良好 / 盤面美品',
    shippingUnit: 1,
    handlingUnit: 2,
    allowSplitSale: true,
    hasNailSheet: true,
    hasManual: true,
    allowPickup: false,
    removalStatus: '未撤去',
    shippingSpecifyDate: '即時手配可',
    warehouseName: '大阪北倉庫',
    ownerUserId: 'user-a',
  },
  {
    id: 102,
    updatedAt: '2025/01/09',
    status: '出品中',
    prefecture: '神奈川県',
    maker: 'SANYO',
    name: 'P大海物語5',
    type: '本体',
    quantity: 10,
    price: 275000,
    removalDate: '2025/02/15',
    replyTime: '1時間',
    sellerName: '湘南スロット',
    note: 'CRユニット付属 / 台車手配可',
    shippingUnit: 1,
    handlingUnit: 1,
    allowSplitSale: true,
    hasNailSheet: false,
    hasManual: true,
    allowPickup: true,
    removalStatus: '撤去済',
    shippingSpecifyDate: '2/20以降',
    warehouseName: '湘南ロジスティクス',
    ownerUserId: 'user-b',
  },
  {
    id: 103,
    updatedAt: '2024/12/28',
    status: '成約済',
    prefecture: '東京都',
    maker: 'KYORAKU',
    name: 'ぱちんこ 新・必殺仕置人S',
    type: '本体',
    quantity: 4,
    price: 198000,
    removalDate: '2025/01/05',
    replyTime: '2時間',
    sellerName: '新宿ステーション',
    shippingUnit: 2,
    handlingUnit: 2,
    allowSplitSale: false,
    hasNailSheet: true,
    hasManual: false,
    allowPickup: false,
    removalStatus: '撤去済',
    shippingSpecifyDate: '応相談',
    warehouseName: '都内第1倉庫',
    ownerUserId: 'user-a',
  },
  {
    id: 104,
    updatedAt: '2025/01/04',
    status: '出品中',
    prefecture: '北海道',
    maker: 'DAIICHI',
    name: 'スマパチ ソードアート・オンライン',
    type: '本体',
    quantity: 3,
    price: 348000,
    removalDate: '2025/02/01',
    replyTime: '45分',
    sellerName: '札幌レジャー館',
    note: '島配線セット相談可',
    shippingUnit: 1,
    handlingUnit: 2,
    allowSplitSale: false,
    hasNailSheet: false,
    hasManual: true,
    allowPickup: false,
    removalStatus: '未撤去',
    shippingSpecifyDate: '2/5出荷目安',
    warehouseName: '札幌ハブ倉庫',
    ownerUserId: 'user-b',
  },
  {
    id: 105,
    updatedAt: '2025/01/10',
    status: '下書き',
    prefecture: '愛知県',
    maker: 'YAMASA',
    name: 'スマスロ モンキーターンV',
    type: 'セルのみ',
    quantity: 8,
    price: 158000,
    removalDate: '2025/03/01',
    replyTime: '1時間',
    sellerName: '名古屋スロット専門館',
    note: 'ヘッドホン端子増設',
    shippingUnit: 2,
    handlingUnit: 2,
    allowSplitSale: true,
    hasNailSheet: false,
    hasManual: true,
    allowPickup: true,
    removalStatus: '未撤去',
    shippingSpecifyDate: '3/3指定可',
    warehouseName: '中部物流センター',
    ownerUserId: 'user-a',
  },
  {
    id: 106,
    updatedAt: '2025/01/02',
    status: '出品中',
    prefecture: '福岡県',
    maker: 'HEIWA',
    name: 'Pルパン三世 THE FIRST',
    type: '本体',
    quantity: 5,
    price: 210000,
    removalDate: '2025/01/25',
    replyTime: '30分',
    sellerName: '博多プラザ',
    shippingUnit: 1,
    handlingUnit: 1,
    allowSplitSale: true,
    hasNailSheet: true,
    hasManual: true,
    allowPickup: false,
    removalStatus: '撤去済',
    shippingSpecifyDate: '1/30以降',
    warehouseName: '九州第2倉庫',
    ownerUserId: 'user-b',
  },
  {
    id: 107,
    updatedAt: '2025/01/11',
    status: '出品中',
    prefecture: '東京都',
    maker: 'FUJI',
    name: 'Pフィーバー マクロスフロンティア4 超銀河LIVE LIGHT ver. スペシャルエディションロングタイトル',
    type: '本体',
    quantity: 4,
    price: 302000,
    removalDate: '2025/02/10',
    replyTime: '45分',
    sellerName: '秋葉原アミューズメント',
    note: 'タイトル長めの表示確認用 / 台枠状態良好',
    shippingUnit: 1,
    handlingUnit: 2,
    allowSplitSale: true,
    hasNailSheet: false,
    hasManual: true,
    allowPickup: true,
    removalStatus: '未撤去',
    shippingSpecifyDate: '応相談',
    warehouseName: '東京湾岸倉庫',
    ownerUserId: 'user-a',
  },
  {
    id: 108,
    updatedAt: '2025/01/07',
    status: '出品中',
    prefecture: '兵庫県',
    maker: 'UNIVERSAL',
    name: 'SLOTバジリスク〜甲賀忍法帖〜絆2 天膳 BLACK EDITION',
    type: '本体',
    quantity: 2,
    price: 185000,
    removalDate: '2024/12/20',
    replyTime: '1時間',
    sellerName: '神戸ベイホール',
    note: '撤去済み / 清掃済',
    shippingUnit: 2,
    handlingUnit: 2,
    allowSplitSale: false,
    hasNailSheet: true,
    hasManual: true,
    allowPickup: false,
    removalStatus: '撤去済',
    shippingSpecifyDate: '即時手配可',
    warehouseName: '阪神ロジステーション',
    ownerUserId: 'user-a',
  },
  {
    id: 109,
    updatedAt: '2025/01/05',
    status: '出品中',
    prefecture: '北海道',
    maker: 'TAKAO',
    name: 'Pゴジラ対エヴァンゲリオン〜G細胞覚醒〜',
    type: '本体',
    quantity: 7,
    price: 318000,
    removalDate: '',
    replyTime: '30分',
    sellerName: '札幌セントラル館',
    note: '撤去未定 / 引取応相談',
    shippingUnit: 1,
    handlingUnit: 1,
    allowSplitSale: true,
    hasNailSheet: false,
    hasManual: false,
    allowPickup: false,
    removalStatus: '未撤去',
    shippingSpecifyDate: '調整中',
    warehouseName: '札幌中央倉庫',
    ownerUserId: 'user-a',
  },
  {
    id: 110,
    updatedAt: '2025/01/06',
    status: '出品中',
    prefecture: '愛知県',
    maker: 'SANKYO',
    name: 'スマスロ とある魔術の禁書目録',
    type: 'セルのみ',
    quantity: 5,
    price: 145000,
    removalDate: '2025/03/12',
    replyTime: '50分',
    sellerName: '名古屋セレクトホール',
    note: '先撤去予定あり / 架台相談可',
    shippingUnit: 1,
    handlingUnit: 2,
    allowSplitSale: true,
    hasNailSheet: true,
    hasManual: true,
    allowPickup: true,
    removalStatus: '未撤去',
    shippingSpecifyDate: '3/15出荷目安',
    warehouseName: '中部第2倉庫',
    ownerUserId: 'user-a',
  },
];
