export type SalesInvoiceItem = {
  inventoryId: string;
  maker?: string;
  productName?: string;
  type?: string;
  quantity: number;
  unitPrice: number;
  amount: number;
  remainingDebt?: number;
  applicationPrefecture?: string;
  applicationDate?: string;
  note?: string;
};

export type SalesInvoice = {
  invoiceId: string;
  createdAt: string;
  issuedDate?: string;
  partnerName: string;
  partnerTitle?: string;
  tel?: string;
  fax?: string;
  buyerName?: string;
  buyerPostalCode?: string;
  buyerAddress?: string;
  buyerRepresentative?: string;
  buyerTel?: string;
  buyerFax?: string;
  staff?: string;
  manager?: string;
  paymentDate?: string;
  invoiceOriginal?: string;
  transferBank?: string;
  transferAccount?: string;
  transferName?: string;
  shippingMethod?: string;
  shippingDate?: string;
  shippingTime?: string;
  tradeMethod?: string;
  tradeDate?: string;
  tradeTime?: string;
  shippingAddress?: string;
  tradeAddress?: string;
  memo?: string;
  shippingInsurance?: number;
  subtotal: number;
  tax: number;
  totalAmount: number;
  items: SalesInvoiceItem[];
  inventoryIds: string[];
};
