import { cookies } from "next/headers";
import Link from "next/link";
import { DEV_USERS } from "@/lib/dev-user/users";
import { prisma } from "@/lib/server/prisma";
import { calculateInventoryProfitRows, parsePagination } from "@/features/inventory/financials";
export default async function ProfitPage({ searchParams }: { searchParams: Record<string, string | string[] | undefined> }) {
const ownerUserId=(await cookies()).get("dev_user_id")?.value??DEV_USERS.A.id; const {page,pageSize,skip,take}=parsePagination(searchParams); const where={ownerUserId}; const [rows,totalCount]=await Promise.all([prisma.inventoryItem.findMany({where,include:{maker:true,purchaseRecords:true,salesRecords:true},orderBy:{updatedAt:"desc"},skip,take}),prisma.inventoryItem.count({where})]);
const payments=await prisma.paymentRecord.findMany({where:{ownerUserId}});
const profits=calculateInventoryProfitRows(rows.map((r)=>({id:r.id,makerName:r.maker?.name??r.makerNameSnapshot,modelName:r.modelNameSnapshot,quantityOnHand:r.quantityOnHand,inventoryStatus:r.inventoryStatus,purchaseRecords:r.purchaseRecords,salesRecords:r.salesRecords,paymentRecords:payments.filter((p)=>[...r.purchaseRecords.map(x=>x.id),...r.salesRecords.map(x=>x.id)].includes(p.sourceId)).map((p)=>({sourceType:p.sourceType,status:p.status}))})));
return <div className="mx-auto max-w-6xl px-4 py-8 text-sm"><h1 className="text-2xl font-bold mb-3">実粗利一覧</h1><Link href="/inventory/financials/profit.csv" className="underline text-blue-600">CSV出力</Link><table className="w-full mt-3 border text-xs"><thead><tr>{["在庫","メーカー","数量","仕入","売上","費用","実粗利","粗利率"].map(h=><th key={h} className="border p-1">{h}</th>)}</tr></thead><tbody>{profits.map(r=><tr key={r.id}><td className="border p-1"><Link href={`/inventory/items/${r.id}`} className="underline">{r.modelName}</Link></td><td className="border p-1">{r.makerName??"-"}</td><td className="border p-1">{r.quantityOnHand}</td><td className="border p-1">{r.totalCost}</td><td className="border p-1">{r.totalSales}</td><td className="border p-1">{r.totalFees}</td><td className="border p-1">{r.realGrossProfit}</td><td className="border p-1">{r.profitRate==null?"-":`${r.profitRate}%`}</td></tr>)}</tbody></table><div className="mt-3 flex gap-3"><span>{totalCount}件</span>{page>1&&<Link className="underline" href={`?page=${page-1}&pageSize=${pageSize}`}>Prev</Link>}{skip+take<totalCount&&<Link className="underline" href={`?page=${page+1}&pageSize=${pageSize}`}>Next</Link>}</div></div>;
}
